services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: happimobi_api
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  api-tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: tester
    container_name: happimobi_api_tests
    environment:
      NODE_ENV: test
  mongo:
    image: mongo:7
    container_name: happimobi_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
